### ISSUE TITLE
Cannot compile the code

### ISSUE THREAD

**Issue by chenweikai** [mtatarchenko/ogn#16]
Hi!

I tried to compile the code but without luck. 
It seems there is some link error to the boost library.
I have successfully compiled the original caffe from caffe's official website, so I should have installed boost correctly.
The following is the beginning part of the error message (the completed message is too long...).
I work on Ubuntu 16.04. 
Any idea how to fix it? Thanks a lot!

CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
CXX/LD -o .build_release/tools/ogn_converter.bin
CXX/LD -o .build_release/tools/upgrade_solver_proto_text.bin
.build_release/tools/ogn_converter.o: In function `register_cmd_options(int, char**)':
ogn_converter.cpp:(.text+0x298): undefined reference to `boost::program_options::options_description::m_default_line_length'
ogn_converter.cpp:(.text+0x2d7): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
ogn_converter.cpp:(.text+0x3c2): undefined reference to `boost::program_options::options_description::add_options()'
ogn_converter.cpp:(.text+0x3e8): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
ogn_converter.cpp:(.text+0x401): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
ogn_converter.cpp:(.text+0x41a): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
ogn_converter.cpp:(.text+0x433): undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
ogn_converter.cpp:(.text+0x43b): undefined reference to `boost::program_options::variables_map::variables_map()'
ogn_converter.cpp:(.text+0x476): undefined reference to `boost::program_options::detail::cmdline::set_options_description(boost::program_options::options_description const&)'
ogn_converter.cpp:(.text+0x488): undefined reference to `boost::program_options::detail::cmdline::style(int)'
ogn_converter.cpp:(.text+0x552): undefined reference to `boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool)'
ogn_converter.cpp:(.text+0x695): undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_options::options_description const&)'
ogn_converter.cpp:(.text+0x6d2): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
ogn_converter.cpp:(.text+0x734): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
ogn_converter.cpp:(.text+0x796): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'

**Comment by chenweikai** [comment]
okay, I solved it myself.
In Makefile, should add "boost_program_options boost_serialization" to LIBRARIES.
In particular, in around Line 181, replace the line with the following:
LIBRARIES += glog gflags protobuf boost_system boost_program_options boost_serialization boost_filesystem m hdf5_serial_hl hdf5_serial

**Comment by tatarchm** [comment]
We actually do not provide support for Makefile build, the recommended build system is CMake. I've updated the readme file with the corresponding information.

**Comment by LongruiDong** [comment]
> okay, I solved it myself.
> In Makefile, should add "boost_program_options boost_serialization" to LIBRARIES.
> In particular, in around Line 181, replace the line with the following:
> LIBRARIES += glog gflags protobuf boost_system boost_program_options boost_serialization boost_filesystem m hdf5_serial_hl hdf5_serial

you saved my day～
It works for me！
